project_id = "ufkacqdvrmapqpsisqai"

[functions.cleanup-ghost-posts]
verify_jwt = false

[functions.random-connect-signaling]
verify_jwt = false

[functions.cleanup-random-connect]
verify_jwt = false
